### ISSUE TITLE
Popup does not work inside detachable modal.

### ISSUE THREAD

**Issue by hvgotcodes** [Semantic-Org/Semantic-UI-Ember#128] opened 2016-08-01 20:31 UTC
I ran into a problem in our app and created a new app with just this plugin in it to reproduce.

I have a route

```
export default Ember.Route.extend({

    actions: {
        showModal(){
            console.log('show')
            Ember.$('.the-modal').modal('show');
        }
    }
});

```

and a template

```
Click <button type="button" {{action "showModal"}}>here</button> for modal.

{{#ui-modal classNames="the-modal" detachable=true}}

    <header>
        <h1 class="ui header">I be a modal.</h1>
    </header>

    <div class="content">
        {{#ui-popup
        tagName="button"
        class="ui button"
        inline=true
        ui_on="click"
        position="bottom center"}}
            Let's see a popup!!
        {{/ui-popup}}

        <div class="ui popup">
            Pop it up!!
        </div>

    </div>

    <div class="actions">
        <button type="button" class="ui button deny">Done</button>
    </div>
{{/ui-modal}}
```

The popup does not appear on click.  If I take `detachabe=true` off the modal,  everything works as expected.

**Comment by aaronbhansen** [comment] 2016-08-02 16:28
Yeah thats a little tricky. The problem is when detachable is false, Semantic-UI keeps the modules html in its current location, which means all the bind events that took place up until now work fine. 

When its not detachable, its moving the html and also breaking some of the previous bindings. 

Modals in ember are a little bit of an outliner, since you render them and then things could change after ember has done all of its work.

We have a plugin that we maintain on the side for better modal support. We might eventually bring it into Semantic-UI-Ember, but are making sure all the bugs are worked first. The repo is https://github.com/unchartedcode/semantic-ui-ember-modal

Add this to your package.json if you want to try it out. 
```
"semantic-ui-ember-modal": "git://github.com/unchartedcode/semantic-ui-ember-modal#673d891d5834f88f63ac1f2caeea3133ed3a62e2"
```

Then in your application template add the following snippet

```
{{#each modals as |modal|}}
  {{component-apply modal.name modal.args}}
{{/each}}
```

There isn't documentation, but the mechanics are pretty easy. You create a new component and extend from ui-modal.

```
import UiModal from 'semantic-ui-ember/components/ui-modal';

export default UiModal.extend({
  onApprove() {
    // do on approve code here
    // return false to stop the modal from closing 
  }
});
```

Then in your template or controller just call

```
<div class="ui button" {{action "open_modal" "component-modal" (hash text="hi")}}>
```

and it should open the modal for you and create the component right then. That may fix your semantic-ui problem, but I don't think we've had a popup in a modal at the moment. The reason I say it max fix the popup, is it handles modal and the creation differently than how you are above. 

If the addon works out for you, we could look at releasing it and making it more public

**Comment by hvgotcodes** [comment] 2016-08-02 17:25
Thank you for the quick reply.  Is there another option, a workaround perhaps?    

We have already created an extension of the modal component so we could make it more accessible for screen readers; if we go that route we would need to move that work over (not a big deal I suppose).  We also have our own way of managing modals so we can expose multiple model instances in a single modal, which would need to be adapted (and a solution similar to your 'open_modal' action.  Point being swapping out our modal implementation would trigger a bunch of other work for us...

**Comment by aaronbhansen** [comment] 2016-08-02 17:36
You could try setting inline to true on the popup, so it didn't try to create it under the body element. 

Or you could tie into the onVisible event and then set a flag to true possibly that wraps the ui-popup to have it only render and show once the modal is visible. Ember would wait to render that block of code until the modal has already been rendered.

Second option seems a little hacky, but just guessing at possible easy solutions that might work for you.

**Comment by hvgotcodes** [comment] 2016-08-02 19:27
@aaronbhansen I added a flag in `didInsertElement` and only render the popup and its associated dom once that flag is set.  Seems to do the trick, thanx for the idea.  I think this still remains an issue but at least we have a work around.

**Comment by aaronbhansen** [comment] 2016-08-02 19:50
Great to hear. Mainly the issue is around Ember and its render cycle. Its a conflict between Ember and Semantic-UI using the dom differently. Unfortunately I don't think it can be fully resolved until we create a modal plugin to render components outside of the main template so that any components in a modal are only rendered once they are injected. I'll close the issue out for now and look revisit it once we add better modal support.

**Closed by aaronbhansen** 2016-08-02 19:50 UTC
