### ISSUE TITLE
Document customizing Semantic UI and including into the ember-cli build process

### ISSUE THREAD

**Issue by khornberg** [Semantic-Org/Semantic-UI-Ember#176] opened 2017-01-09 15:55 UTC
There are several questions about how to include a customized version of Semantic UI in an Ember project using Semantic-UI-Ember.

**Comment by khornberg** [comment] 2017-01-09 16:01
Relates to #162 #171 #58 #104 #7 #120 #114

**Comment by Panman8201** [comment] 2017-01-11 14:17
I'm just curious, what exactly does everyone want to be able to customize with SUI? I personally haven't dealt with custom builds with SUI, but have done Less and Sass before.

**Comment by irminsul** [comment] 2017-01-13 11:41
Dealing with custom Semantic UI builds in an Ember app is actually quite simple if you are able to live without full integration into `ember build`. We have been doing this in one of our apps for a couple of months now and have not encountered any issues so far.

When you run `npm install --save-dev semantic-ui `, select the "Custom (Customize all src/dist values)" option and answer the questions as follows:

- Is this your project folder? (select your project folder or accept the default)
- Where should we put Semantic UI inside your project? `vendor/semantic-ui`
- What components should we include in the package? (select the components you need or accept the default)
- Should we set permissions on outputted files? `No`
- Do you use a RTL (Right-To-Left) language? (select the option that is appropriate for your project)
- Where should we put your site folder? `../../app/styles/semantic-ui/`
- Where should we output a packaged version? `../../bower_components/semantic-ui/dist`
- Where should we output compressed components? `../../bower_components/semantic-ui/dist/components/`
- Where should we output uncompressed components? `../../bower_components/semantic-ui/dist/components/`

After that, open the generated `semantic.json` file and update the values for `output.themes` and `clean` so that they also refer to `../../bower_components/*`:

```json
{
  "base": "vendor/semantic-ui",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "../../app/styles/semantic-ui/",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "../../bower_components/semantic-ui/dist/",
      "uncompressed": "../../bower_components/semantic-ui/dist/components/",
      "compressed": "../../bower_components/semantic-ui/dist/components/",
      "themes": "../../bower_components/semantic-ui/dist/themes/"
    },
    "clean": "../../bower_components/semantic-ui/dist/"
  },
  "permission": false,
  "autoInstall": true,
  "rtl": false,
  "components": [
    "accordion",
    "button",
    "calendar",
    "checkbox",
    "container",
    "dimmer",
    "divider",
    "dropdown",
    "form",
    "grid",
    "header",
    "icon",
    "image",
    "input",
    "label",
    "loader",
    "menu",
    "message",
    "modal",
    "popup",
    "reset",
    "search",
    "site",
    "step",
    "table",
    "transition"
  ],
  "version": "2.2.7"
}
```

Finally, you can run `gulp build && gulp watch` from the `vendor/semantic-ui` folder alongside `ember serve`. Gulp will output the SUI files to `bower_components/semantic-ui` where ember-cli will detect any changes and livereload the styles.

**Comment by joebartels** [comment] 2017-01-29 20:18
@irminsul that worked well for me! A few things to note for others is that all the prompts _following this question_:
> Where should we put Semantic UI inside your project?

are expecting a path relative to the project path _(in this case`vendor/semantic-ui`)_. You use relative paths in your walkthrough but I misinterpreted the intent.

You may have to `mkdir` the directories in advance.

And if you happen to have `semantic-ui` entry in your bower.json file _(from previous fiddling)_ then ember-cli-dependency-checker may fail _(without specifying which dependency is at fault)_:
```bash
TypeError: Invalid Version: *
```

To fix this, either remove the entry from bower.json or just `bower install semantic-ui` in some temporary directory and `cp` the .bower.json file into your app's `bower_components/semantic-ui/` directory

**Comment by bockscar** [comment] 2017-02-02 01:34
@irminsul That worked great. Thank you!

**Comment by aaronbhansen** [comment] 2017-02-02 16:43
If someone wants to put together a documentation PR we can get it merged in to help others.

**Comment by kiesia** [comment] 2017-02-04 01:43
Awesome, I can confirm that the above works. 🙂 To get the icons displaying I also had to set `@fontPath  : "../../assets/themes/default/assets/fonts"` in `icon.variables`.

**Comment by allthesignals** [comment] 2018-02-03 21:10
@irminsul @kiesia what is the approach for production builds of Ember? I've added a `postinstall` step which runs `gulp build` in the semantic-ui directory, and that works correctly, but I'm not seeing my custom styles _in production_ - this works fine in development.

FWIW, I am using site.variables (instead of site.overrides) because that's the only thing that responds to my changes.

Thanks for any help!

**Comment by allthesignals** [comment] 2018-02-03 21:35
@joebartels 

> TypeError: Invalid Version: *
To fix this, either remove the entry from bower.json or just bower install semantic-ui in some temporary directory and cp the .bower.json file into your app's bower_components/semantic-ui/ directory

Are these steps that should be added to a project-specific README? What's going on here?

**Comment by championswimmer** [comment] 2018-02-25 13:35
If you use v3.0.0-beta3
```
ember install semantic-ui-ember@beta
```

You can run the following blueprint - 
```
ember g semantic-ui-custom
```

Which will setup a basic apparatus for using custom Semantic UI Theme via the `/semantic` directory.

**Comment by gibso** [comment] 2018-03-05 17:52
@championswimmer 

when i enter `ember g semantic-ui-custom` i get the following:
```
Unexpected identifier


Stack Trace and Error Report: /tmp/error.dump.39c9623b8626533a8d228e37ba4f487d.log
```
Stack Trace is the following:
```
  - stack: /usr/src/app/node_modules/semantic-ui-ember/blueprints/semantic-ui-custom/index.js:15
  async afterInstall(options) {
        ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Function.Blueprint.load (/usr/src/app/node_modules/ember-cli/lib/models/blueprint.js:1284:31)
    at Function.Blueprint.lookup (/usr/src/app/node_modules/ember-cli/lib/models/blueprint.js:1261:24)
```

Any idea how this can get fixed?
I'm using ember-cli 3.0.0  with node 6.4.0 and semantic-ui-ember 3.0.0-beta3 in a docker container.

Thanks for your works ;-)

**Comment by championswimmer** [comment] 2018-03-06 02:03
It doesn't work with node 6, but node 8

Will fix it.

**Comment by championswimmer** [comment] 2018-03-06 02:30
@gibso can you try with `v3.0.0-beta4` ?

**Comment by gibso** [comment] 2018-03-06 20:28
@championswimmer that did the trick! thank you so much!

**Closed** 2018-03-16 18:36 UTC

**Comment by mdbr000** [comment] 2019-02-19 02:45
can someone explain exactly how to use the blueprint that is generated by `ember g semantic-ui-custom` ? 

i ran it and now have the blueprint sitting in my semantic/ folder, but running with `ember s` shows none of the changes i have applied to files within the semantic/ folder.

i have tried building with `gulp build` to no effect.

is there some extra linkage that needs to occur in order to get this to work?  the official docs don't give any detail.
